name: "Generate Actions to build Nupp images"

on:
  push:
    branches:
      - "main"
    paths:
      - "node/build.rb"
      - "node/linux"

jobs:
  generate-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Render latest template
        run: |
          cd node
          ruby build.rb
      - uses: seanmiddleditch/gha-publish-to-git@master
        with:
          branch: main
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          github_pat: ${{ secrets.WORKFLOW_TOKEN }}
          commit_author: "cristiano.rosetti@gmail.com"
          commit_message: Generated new Action to build Nupp images
