name: "Generate Actions to build Nupp images"
on:
  push:
    branches:
      - main
    paths:
      - build.rb
      - linux

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Render latest template
        run: |
          ruby node/build.rb
      - uses: seanmiddleditch/gha-publish-to-git@main
        with:
          branch: main
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          github_pat: ${{ secrets.WORKFLOW_TOKEN }}
          commit_author: "cristiano.rosetti@gmail.com"
          commit_message: Generated new Action to build Nupp images
